version: "3.8"
services:
  ant-hurry-redis:
    container_name: ant-hurry-redis
    image: redis:6
    environment:
      - TZ=Asia/Seoul
    ports:
      - "6379:6379"
      -
  ant-hurry-database:
    container_name: ant-hurry-database
    image: mariadb:latest
    environment:
      - MARIADB_DATABASE=${DATASOURCE_USERNAME}
      - MARIADB_ROOT_PASSWORD=${DATASOURCE_PASSWORD}
      - TZ=Asia/Seoul
    volumes:
      - ./database/config:/etc/mysql/conf.d
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
      -
  ant-hurry-app:
    container_name: ant-hurry-app
    build: .
    depends_on:
      - ant-hurry-database
      - ant-hurry-redis
    image: ant-hurry-app
    ports:
      - "8080:8080"
    restart: always

  ant-hurry-nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    environment:
      TZ: "Asia/Seoul"
      DB_MYSQL_HOST: "172.17.0.1"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: ${DATASOURCE_USERNAME}
      DB_MYSQL_PASSWORD: ${DATASOURCE_PASSWORD}
      DB_MYSQL_NAME: ${NGINX_NAME}
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
      -
  ant-hurry-jenkins:
    depends_on:
      - ant-hurry-database
    container_name: ant-hurry-jenkins
    image: jenkins/jenkins:jdk17
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    ports:
      - "8081:8080"
    user: root
    restart: unless-stopped