spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: '${spring.data.mongodb.database}'
  sql:
    init:
      data-locations: classpath:data_h2.sql
      mode: always
