spring:
  datasource:
    driver-class-name: '${custom.prod_database.driver-class-name}'
    url: '${custom.prod_database.url}'
    username: '${custom.prod_database.username}'
    password: '${custom.prod_database.password}'
  jpa:
    hibernate:
      ddl-auto: validate

  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB
      location: ${custom.prod_fileLocation}
      enabled: true
  data:
    redis:
      host: ${custom.redis.host}
      port: ${custom.redis.port}
custom:
  site:
    baseUrl: https://www.anthurry.shop